#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0206, AA0218, AA0228, AL0424, AW0006 // ForNAV settings
dotnet // --> Reports ForNAV Autogenerated code - do not delete or modify
{
    assembly("ForNav.Reports.6.3.0.2259")
    {
        type(ForNav.Report_6_3_0_2259; ForNavReport51516357_v6_3_0_2259) { }
    }
} // Reports ForNAV Autogenerated code - do not delete or modify -->

Report 50357 "Off Limit Transactions Report"
{
    RDLCLayout = 'Layouts/OffLimitTransactionsReport.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Audit Suspicious Transactions"; "Audit Suspicious Transactions")
        {
            column(ReportForNavId_1; 1) { } // Autogenerated by ForNav - Do not delete
            column(Company_Name; Company.Name)
            {
            }
            column(Company_Address; Company.Address)
            {
            }
            column(Company_City; Company.City)
            {
            }
            column(Company_Picture; Company.Picture)
            {
            }
            column(Company_Email; Company."E-Mail")
            {
            }
            column(Company_Address_2; Company."Address 2")
            {
            }
            column(Company_Phone_No; Company."Phone No.")
            {
            }
            column(Company_Fax_No; Company."Fax No.")
            {
            }
            column(SN; SN)
            {
            }
            column(DocumentNo_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Document No")
            {
            }
            column(MonthTurnOverAmount_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Month TurnOver Amount")
            {
            }
            column(MaxCreditsAllowable_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Max Credits Allowable")
            {
            }
            column(TransactedBy_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Transacted By")
            {
            }
            column(TransactionAmount_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Transaction Amount")
            {
            }
            column(TransactionType_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Transaction Type")
            {
            }
            column(TransactionDate_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Transaction Date")
            {
            }
            column(AccountName_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Account Name")
            {
            }
            column(AccountNo_AuditSuspiciousTransactions; "Audit Suspicious Transactions"."Account No")
            {
            }
            column(Variance; Variance)
            {
            }
            dataitem(Transactions; Transactions)
            {
                DataItemLink = No = field("Document No");
                column(ReportForNavId_2; 2) { } // Autogenerated by ForNav - Do not delete
                column(TransactionDeclaration_Transactions; Transactions."Transaction Declaration")
                {
                }
                column(EvidenceObtained_Transactions; Transactions."Evidence Obtained")
                {
                }
                column(TransactionType_Transactions; Transactions."Transaction Type")
                {
                }
                column(MemberNo_Transactions; Transactions."Member No")
                {
                }
                column(CheckedBy_Transactions; Transactions."Checked By")
                {
                }
                column(MemberName_Transactions; Transactions."Member Name")
                {
                }
            }
            trigger OnPreDataItem();
            begin
                Company.Get();
                Company.CalcFields(Picture);
            end;

            trigger OnAfterGetRecord();
            begin
                SN := SN + 1;
                Variance := "Audit Suspicious Transactions"."Transaction Amount" - "Audit Suspicious Transactions"."Max Credits Allowable";
            end;

        }
    }

    requestpage
    {


        SaveValues = false;
        layout
        {
            area(content)
            {
                group(Options)
                {
                    Caption = 'Options';
                    field(ForNavOpenDesigner; ReportForNavOpenDesigner)
                    {
                        ApplicationArea = Basic;
                        Caption = 'Design';
                        Visible = ReportForNavAllowDesign;
                        trigger OnValidate()
                        begin
                            ReportForNav.LaunchDesigner(ReportForNavOpenDesigner);
                            CurrReport.RequestOptionsPage.Close();
                        end;

                    }
                }
            }
        }

        actions
        {
        }
        trigger OnOpenPage()
        begin
            ReportForNavOpenDesigner := false;
        end;
    }

    trigger OnInitReport()
    begin
        ;
        ReportsForNavInit;

    end;

    trigger OnPostReport()
    begin
        ;
        ReportForNav.Post;
    end;

    trigger OnPreReport()
    begin
        ;
        ReportsForNavPre;
    end;

    var
        Company: Record "Company Information";
        SN: Integer;
        Variance: Decimal;

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    var
        [WithEvents]
        ReportForNav: DotNet ForNavReport51516357_v6_3_0_2259;
        ReportForNavOpenDesigner: Boolean;
        [InDataSet]
        ReportForNavAllowDesign: Boolean;

    local procedure ReportsForNavInit();
    var
        ApplicationSystemConstants: Codeunit "Application System Constants";
        addInFileName: Text;
        tempAddInFileName: Text;
        path: DotNet Path;
        ReportForNavObject: Variant;
    begin
        addInFileName := ApplicationPath() + 'Add-ins\ReportsForNAV_6_3_0_2259\ForNav.Reports.6.3.0.2259.dll';
        if not File.Exists(addInFileName) then begin
            tempAddInFileName := path.GetTempPath() + '\Microsoft Dynamics NAV\Add-Ins\' + ApplicationSystemConstants.PlatformFileVersion() + '\ForNav.Reports.6.3.0.2259.dll';
            if not File.Exists(tempAddInFileName) then
                Error('Please install the ForNAV DLL version 6.3.0.2259 in your service tier Add-ins folder under the file name "%1"\\If you already have the ForNAV DLL on the server, you should move it to this folder and rename it to match this file name.', addInFileName);
        end;
        ReportForNavObject := ReportForNav.GetLatest(CurrReport.OBJECTID, CurrReport.Language, SerialNumber, UserId, CompanyName);
        ReportForNav := ReportForNavObject;
        ReportForNav.Init();
    end;

    local procedure ReportsForNavPre();
    begin
        ReportForNav.OpenDesigner := ReportForNavOpenDesigner;
        if not ReportForNav.Pre() then CurrReport.Quit();
    end;

    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
