#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0206, AA0218, AA0228, AL0424, AW0006 // ForNAV settings
//51516874_v6_3_0_2259) { }
// Autogenerated code - do not delete or modify -->

Report 50874 "Send Member Monthly Statement"
{
    RDLCLayout = 'Layouts/SendMemberMonthlyStatement.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem(Customer; Customer)
        {
            DataItemTableView = where("Email Indemnified" = filter(true), "E-Mail" = filter(<> ''));
            column(ReportForNavId_1; 1) { } // Autogenerated by ForNav - Do not delete
            trigger OnPreDataItem();
            begin
                FromDate := CalcDate('-1M', WorkDate);
                ToDate := CalcDate('-1D', WorkDate);
                VarDateFilter := Format(FromDate) + '..' + Format(ToDate);
            end;

            trigger OnAfterGetRecord();
            begin
                ObjMember.Reset;
                ObjMember.SetRange(ObjMember."Email Indemnified", true);
                ObjMember.SetFilter(ObjMember."E-Mail", '<>%1&%2', '', '*@*.*');
                ObjMember.SetFilter(ObjMember."Date Filter", VarDateFilter);
                ObjMember.SetRange(ObjMember."No.", Customer."No.");
                if ObjMember.FindSet then begin
                    Filename := '';
                    Filename := 'D:\Member Statements\Member Account Statement - ' + ObjMember."No." + '.pdf';
                    Report.SaveAsPdf(Report::"Member Account Statement(App)", Filename, ObjMember);
                end;
            end;

        }
    }

    requestpage
    {


        SaveValues = false;
        layout
        {
            area(content)
            {
                group(Options)
                {
                    Caption = 'Options';

                }
            }
        }

        actions
        {
        }
        trigger OnOpenPage()
        begin
            //:= false;
        end;
    }

    trigger OnInitReport()
    begin
        ;


    end;

    trigger OnPostReport()
    begin
        ;

    end;

    trigger OnPreReport()
    begin
        ;

    end;

    var
        ObjMember: Record Customer;
        VarMemberEmail: Text[100];
        Filename: Text;
        SMTPSetup: Record "SMTP Mail Setup";
        VarMemberName: Text;
        SurestepFactory: Codeunit "SURESTEP Factory";
        VarEmailSubject: Text;
        VarEmailBody: Text;
        VarDateFilter: Text;
        FromDate: Date;
        ToDate: Date;

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    //51516874_v6_3_0_2259;






    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
