#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0206, AA0218, AA0228, AL0424, AW0006 // ForNAV settings
//51516915_v6_3_0_2259) { }
// Autogenerated code - do not delete or modify -->

Report 50915 "Cases Register."
{
    RDLCLayout = 'Layouts/CasesRegister..rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Cases Management"; "Cases Management")
        {
            DataItemTableView = sorting("Case Number") where(Status = filter(<> Open));
            column(ReportForNavId_3182; 3182) { } // Autogenerated by ForNav - Do not delete
            column(FORMAT_TODAY_0_4_; Format(Today, 0, 4))
            {
            }
            column(COMPANYNAME; COMPANYNAME)
            {
            }

            column(UserId; UserId)
            {
            }
            column(Vendor__No__; "Cases Management"."Case Number")
            {
            }
            column(Vendor_Name; "Cases Management"."Type of cases")
            {
            }
            column(Vendor__Account_Type_; "Cases Management"."Responsibility Center")
            {
            }
            column(Vendor_Status; "Cases Management".Status)
            {
            }
            column(Vendor__Balance__LCY__; "Cases Management"."Member No.")
            {
            }
            column(Vendor__ID_No__; "Cases Management"."Resource Assigned")
            {
            }
            column(Rno; Rno)
            {
            }
            column(Vendor__Staff_No_; "Cases Management"."Case Description")
            {
            }
            column(Vendor__Balance__LCY___Control1102760019; "Cases Management"."Action Taken")
            {
            }
            column(Accounts_BalancesCaption; Accounts_BalancesCaptionLbl)
            {
            }
            column(CurrReport_PAGENOCaption; CurrReport_PAGENOCaptionLbl)
            {
            }
            trigger OnPreDataItem();
            begin
                /*
				//Hide Balances
				IF UsersID.GET(USERID) THEN BEGIN
				IF UsersID."Show Hiden" = FALSE THEN
				Vendor.SETRANGE(Vendor.Hide,FALSE);
				END;
				//Hide Balances
				 NAVVSFOX.RESET;
				 NAVVSFOX.SETRANGE(NAVVSFOX."Account No.",Vendor."No.");
				 IF NAVVSFOX.FIND('-') THEN BEGIN
				NAVVSFOX."SBal - Navision":=Vendor."Balance (LCY)";
				NAVVSFOX."ABal-FOX":=Vendor."Fosa Loan Bal.";
				NAVVSFOX.MODIFY;
				END;
				*/

            end;

            trigger OnAfterGetRecord();
            begin
                /*
				{
				RCount:=RCount+1;
				{
				//Hide Balances
				 NAVVSFOX.RESET;
				 NAVVSFOX.SETRANGE(NAVVSFOX."Account No.",Vendor."No.");
				 IF NAVVSFOX.FIND('-') THEN BEGIN
				 REPEAT
				NAVVSFOX."SBal - Navision":=Vendor."Balance (LCY)";
				NAVVSFOX."ABal-Navision":=Vendor."Fosa Loan Bal.";
				NAVVSFOX.Variance:=NAVVSFOX."SBal - Navision"-NAVVSFOX."SBal - FOX";
				NAVVSFOX.MODIFY;
				UNTIL NAVVSFOX.NEXT=0;
				END;
				}
				}
				RCount:=RCount+1;
				//Hide Balances
				 NAVVSFOX.RESET;
				 NAVVSFOX.SETRANGE(NAVVSFOX."Account No.",Vendor."No.");
				 IF NAVVSFOX.FIND('-') THEN BEGIN
				 REPEAT
				{
				NAVVSFOX."SBal - Navision":=0;
				NAVVSFOX.Variance:=0;
				}
				NAVVSFOX."SBal - Navision":=Vendor."Balance (LCY)";
				NAVVSFOX."ABal-Navision":=Vendor."Fosa Loan Bal.";
				NAVVSFOX.Variance:=ROUND(NAVVSFOX."SBal - Navision"-NAVVSFOX."SBal - FOX",1);
				NAVVSFOX."Variance 2":=NAVVSFOX."ABal-Navision"-NAVVSFOX."ABal-FOX";
				IF NAVVSFOX.Variance>NAVVSFOX."Variance 2" THEN BEGIN
				NAVVSFOX.VARIANCE3:=NAVVSFOX."ABal-Navision"-NAVVSFOX."ABal-FOX";
				END;
				NAVVSFOX.MODIFY;
				UNTIL NAVVSFOX.NEXT=0;
				END;
				*/
                Rno := Rno + 1;

            end;

        }
    }

    requestpage
    {


        SaveValues = false;
        layout
        {
            area(content)
            {
                group(Options)
                {
                    Caption = 'Options';

                }
            }
        }

        actions
        {
        }
        trigger OnOpenPage()
        begin
            //:= false;
        end;
    }

    trigger OnInitReport()
    begin
        ;


    end;

    trigger OnPostReport()
    begin
        ;

    end;

    trigger OnPreReport()
    begin
        ;

    end;

    var
        AccountType: Record "Account Types-Saving Products";
        UsersID: Record User;
        RCount: Integer;
        Rno: Integer;
        Accounts_BalancesCaptionLbl: label 'Accounts Balances';
        CurrReport_PAGENOCaptionLbl: label 'Page';
        Account_No_CaptionLbl: label 'Account No.';
        No_CaptionLbl: label 'No.';

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    //51516915_v6_3_0_2259;






    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
